### ISSUE TITLE
Ricetta

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/liste#1]
creare una pagina ricetta.html
in cui sia spiegato come eseguire una ricetta
(lista degli ingredienti e passi da compiere)

**Comment by FabioZTessitore** [comment]
Dopo aver infornato hai riaperto `<li>' invece di chiuderlo.
Cmq ok, andiamo avanti.

ps togli bgcolor da body, si usava 2000 anni fa

**Comment by Teodoro777** [comment]
Pure quello 2000 anni fa!! E che uso per mettere un minimo di colore?

2016-05-07 15:30 GMT+02:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
al momento niente. Quando faremo i fogli di stile metterai tutti i colori che vuoi.
Piuttosto metti qualche classe e qualche id. Ricordi l'esercizio sui tweets?

**Comment by Teodoro777** [comment]
Sisi

2016-05-07 18:41 GMT+02:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by Teodoro777** [comment]
In questo caso dove c'azzeccavano di più?

Il giorno 7 maggio 2016 18:47, Teodoro Coluccio <teodoro.coluccio@gmail.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
mi devi riaggiungere
